[package]
name = "unhaunter"
version = "0.1.0"
edition = "2021"
default-run = "unhaunter"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.13.0"
bevy_framepace = "0.15"
rand = "0.8"
enum-iterator = "2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
image = "0.24.5"
regex = "1.7.1"
tiled = "0.11.2"
clap = "4.4.8"
fastapprox = "0.3.1"
anyhow = "1.0.79"
ordered-float = "4.2.0"
bevy-persistent = { version = "0.5.0", features = ["all"] }

# Enable only a small amount of optimization in debug mode
[profile.dev]
opt-level = 2

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3


[[bin]]
name = "unhaunter"
path = "src/main.rs"

[[bin]]
name = "materials"
path = "src/materials.rs"
