[package]
name = "fasttext_explorer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fasttext = "0.7.8"


# NOTE: To run this, use `cargo run -p fasttext_explorer` from the unhaunter folder.
