name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  quality-gate:
    name: Quality Gate
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy
    
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-
    
    - name: Make scripts executable
      run: chmod +x scripts/*.sh
    
    - name: Run quality checks
      run: |
        echo "::group::Code Quality Checks"
        ./scripts/lint.sh
        echo "::endgroup::"
    
    - name: Run tests
      run: |
        echo "::group::Unit Tests"
        ./scripts/test.sh
        echo "::endgroup::"
    
    - name: Build release
      run: |
        echo "::group::Release Build"
        ./scripts/build.sh
        echo "::endgroup::"
